### ISSUE TITLE
Usage Crash...or I'm doing something wrong.

### ISSUE THREAD

**Issue by CleanCut** [jonschlinkert/is-relative#5]
With the caveat that it's probably my mistake since I'm a backend developer dipping my toes into the TypeScript / NPM / VS Code extension world to tweak a VS Code extension...

When I tried to use `is-relative` in [this extension](https://github.com/castwide/vscode-solargraph/blob/5ea60561bbbd8a88fd5311c806838504ace7a7a5/src/extension.ts#L9), it crashed on that line silently. Why silently? Most likely there's something I need to learn to do in VS Code to enable the crash to reach the UI. 🤷🏼‍♂️ 

I was able to get my code working by replacing the [`import isRelative from 'is-relative';`](https://github.com/castwide/vscode-solargraph/blob/5ea60561bbbd8a88fd5311c806838504ace7a7a5/src/extension.ts#L9) line with [this function](https://github.com/castwide/vscode-solargraph/blob/191cbb278dcae11646bdbe82eb725a6c3949fff2/src/extension.ts#L13-L15) I constructed from digging through the code in this module (and it's dependencies):

```typescript
let isRelative = function (path: string) {
	return !/^[\\\/]{2,}[^\\\/]+[\\\/]+[^\\\/]+/.test(path) && !/^([a-z]:)?[\\\/]/i.test(path);
}
```

If someone can spot what I did wrong and let me know, that would be great!  Or if `is-relative` actually is broken, then maybe this really is a bug report. Either way works. 😄

**Comment by doowb** [comment]
Since `is-relative` would normally be used in Node.js with the [following syntax](https://github.com/jonschlinkert/is-relative#usage):

```js
const isRelative = require('is-relative');
```

You "should" be able to use the "import" syntax like this:

```ts
import * as isRelative from 'is-relative';
```

From the linked issue, on the other repo, it looks like you were also dealing with different versions of TypeScript. If I remember correctly, older versions of TypeScript had different ways of importing Common JS style modules, but I don't remember what those were.

Since, this is most likely an "import syntax" or TypeScript compiler configuration issue, I'm going to close this here. If you're able to see any actual error messages and determine that it's due to a bug in `is-relative`, feel free to reopen this issue.

**Comment by CleanCut** [comment]
Sure thing, thanks for the suggested different syntax!

**Comment by CleanCut** [comment]
> You "should" be able to use the "import" syntax like this:
> 
> ```ts
> import * as isRelative from 'is-relative';
> ```

Today I circled back around to this and tried it in https://github.com/castwide/vscode-solargraph/pull/215 -- and it worked perfectly!  Thanks! ❤️

**Comment by doowb** [comment]
Awesome! I'm glad it works.
